# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db? serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
    #连接超时时间（毫秒）
    timeout: 5000
#开启驼峰命名匹配映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: cn.knightzz.entity