# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db? serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
#开启驼峰命名匹配映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: cn.knightzz.entity